### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by Z-Shang** [vczh-libraries/XGac#1]
$ make
[  3%] Building CXX object CMakeFiles/GacUIX11Cairo.dir/home/zshang/Program/XGac/X11Cairo/NativeWindow/Xlib/XlibNativeController.cpp.o
In file included from /usr/include/X11/Xlibint.h:42:0,
                 from /home/zshang/Program/XGac/X11Cairo/NativeWindow/Xlib/ServicesImpl/../XlibXRecordMouseHookHelper.h:8,
                 from /home/zshang/Program/XGac/X11Cairo/NativeWindow/Xlib/ServicesImpl/XlibNativeWindowService.h:7,
                 from /home/zshang/Program/XGac/X11Cairo/NativeWindow/Xlib/XlibNativeController.cpp:5:
/usr/include/X11/Xproto.h:458:5: error: declaration does not declare anything [-fpermissive]
     BOOL override;
     ^
/usr/include/X11/Xproto.h:1063:6: error: declaration does not declare anything [-fpermissive]
      BOOL override;
      ^
/usr/include/X11/Xproto.h:1087:6: error: declaration does not declare anything [-fpermissive]
      BOOL override;
      ^
/usr/include/X11/Xproto.h:1098:6: error: declaration does not declare anything [-fpermissive]
      BOOL override;
      ^
/usr/include/X11/Xproto.h:1106:6: error: declaration does not declare anything [-fpermissive]
      BOOL override;
      ^
CMakeFiles/GacUIX11Cairo.dir/build.make:307: recipe for target 'CMakeFiles/GacUIX11Cairo.dir/home/zshang/Program/XGac/X11Cairo/NativeWindow/Xlib/XlibNativeController.cpp.o' failed
make[2]: **\* [CMakeFiles/GacUIX11Cairo.dir/home/zshang/Program/XGac/X11Cairo/NativeWindow/Xlib/XlibNativeController.cpp.o] Error 1
CMakeFiles/Makefile2:311: recipe for target 'CMakeFiles/GacUIX11Cairo.dir/all' failed
make[1]: **\* [CMakeFiles/GacUIX11Cairo.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by milizhang** [comment]
@Z-Shang 

The type BOOL used in Xproto should have been defined in Xmd.h. Could you check your Xmd.h and see if it includes the definition?

Should be something like 
typedef unsigned char  CARD8;
......
typedef CARD8       BOOL;

**Comment by Z-Shang** [comment]
@milizhang
yes it does, 
114 typedef unsigned char CARD8;
120 typedef CARD8    BOOL;

**Comment by milizhang** [comment]
@Z-Shang 

And since I have included Xmd.h it should not have this kind of problem.
I will investigate this issue from my side. What kind of environment are you testing on?

**Comment by Z-Shang** [comment]
@milizhang

Arch Linux, everything is the latest version

**Comment by milizhang** [comment]
@Z-Shang

Now I fully understand what exactly happened. `override` is a C++ keyword. 
I am surprised why I did not get this error before. Let me think about some way to fix this.

**Comment by Z-Shang** [comment]
I didn't even realized that...what compiler do you use

**Comment by milizhang** [comment]
@Z-Shang 

And even worse @vczh defined override as a macro of nothing under unix compilers, for unknown reason.
Now I think I know how to handle this.

**Comment by Z-Shang** [comment]
@milizhang

I see...
(but how did you test it under Linux Mint and OS X

**Comment by milizhang** [comment]
@Z-Shang 

My bad. Because previously I only tested it under clang. gcc is quite slow when compiling the combined GacUI files.

**Comment by Z-Shang** [comment]
@milizhang

Got it, I can help to test after you fix it, I'm gonna do homework now...

**Comment by milizhang** [comment]
@Z-Shang 

Check these commits out: 308402bc5afa232bd2b37a6a709b56a8e3dd9ed5 7018d998b2a8936b8b8f104ac06da155e950a0de
Should compile now with gcc. Thanks for the help.
